### ISSUE TITLE
拉下来,跑不起来,佬

### ISSUE THREAD

**Issue by lydlovezjr** [walgr/Quick#3]
![微信截图_20240326171031](https://github.com/walgr/Quick/assets/19246347/a0890dce-ec8e-409f-bcdf-f92dd55e57c7)
![微信截图_20240326171036](https://github.com/walgr/Quick/assets/19246347/83b12e7a-6429-45f6-baab-058c2da714b8)

**Comment by walgr** [comment]
远程引用控制(IS_REMOTE)已关，可以运行了。
